# Generated by Django 5.1.1 on 2024-09-15 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co_authors', models.BooleanField(default=False)),
                ('journal_name', models.CharField(max_length=200)),
                ('article_title', models.CharField(max_length=200)),
                ('volume_issue', models.CharField(max_length=50)),
                ('pages', models.CharField(max_length=50)),
                ('pub_date', models.DateField()),
                ('impact_factor', models.FloatField(blank=True, null=True)),
                ('published', models.BooleanField(default=False)),
                ('indexed', models.BooleanField(default=False)),
                ('index_info', models.CharField(blank=True, max_length=200, null=True)),
                ('doi', models.CharField(blank=True, max_length=100, null=True)),
                ('h_index', models.IntegerField(blank=True, null=True)),
                ('issn', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('faculty_id', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
