# Generated by Django 5.1.1 on 2024-09-13 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ksrmceKPI', '0002_profile_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_author', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=100)),
                ('co_authors', models.BooleanField(default=False)),
                ('name_of_journal', models.CharField(max_length=200)),
                ('title_of_article', models.CharField(max_length=200)),
                ('volume_issue', models.CharField(max_length=50)),
                ('pages_no', models.CharField(max_length=50)),
                ('publication_date', models.DateField()),
                ('impact_factor_sjr', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('published', models.BooleanField(default=False)),
                ('indexed', models.BooleanField(default=False)),
                ('sci_scopus_wos', models.CharField(blank=True, max_length=100, null=True)),
                ('doi', models.CharField(blank=True, max_length=100, null=True)),
                ('h_index', models.IntegerField(blank=True, null=True)),
                ('issn_no', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
