# Generated by Django 5.1.1 on 2024-09-13 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ksrmceKPI', '0003_kpi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpi',
            name='co_authors',
            field=models.CharField(max_length=100),
        ),
    ]
